language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-template *
  - mkdir -p deploy
  - mv spring-template.zip deploy/spring-template.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-template-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: discphy/spring.template
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-template-deploy
    key: spring-template.zip
    bundle_type: zip
    application: spring-template
    deployment_group: spring-template-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: discphy/spring.template
      branch: master

notifications:
  email:
    recipients:
      - dinophy@nate.com