spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      data-locations: classpath:data-h2.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:spring_template
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: real