spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:open_kakao
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
